name: Docker Build & Push

on:
  push:
  workflow_dispatch:

env:
  PROJECT: frps

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 设置版本标签
      - name: Set Docker tag
        id: tag
        run: |
          VERSION=$(awk -F'=' '/ENV VERSION/{gsub(/ /,"",$2); print $2}' Dockerfile || echo "")
          if [ -z "$VERSION" ]; then
            VERSION=$(date +%Y%m%d)
          fi
          echo "TAG=$VERSION" >> $GITHUB_ENV

      # 3️⃣ 调试输出，确认变量正确
      - name: Debug variables
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
          echo "PROJECT=${{ env.PROJECT }}"
          echo "TAG=${{ env.TAG }}"

      # 4️⃣ 设置 QEMU（支持多平台）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 5️⃣ 设置 Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6️⃣ 登录 Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7️⃣ 构建并推送镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT }}:${{ env.TAG }}

      # 8️⃣ 可选：同步 README 到 Docker Hub
      - name: Sync README.md to Docker Hub
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT }}
          readme: "./README.md"
